### ISSUE TITLE
Support for alpine image

### ISSUE THREAD

**Issue by cniweb** [WASdev/ci.docker#107]
Add images with apline linux (as separate tag):
https://hub.docker.com/_/alpine/

**Comment by davidcurrie** [comment]
Hi Christian - I'd like to understand a little bit more about your request (as we have considered an Alpine base image before). What is the driving factor in wanting an Alpine base? Image size or something else? The reason for asking is that the IBM JRE is glibc based. If you look at the ibmjava official image you'll see that the jre-alpine tag is therefore still 184 MB (still a saving from 310 MB for the Ubuntu image). We also have the sfj-alpine image which strips out a bunch of things from the JRE which we don't anticipate being of use in a server-side environment and that brings the image size down to 101 MB (bringing it more in to line with the openjdk:8-jre-alpine image of 108 MB).

The second question relates to support. Neither Alpine nor the Small Footprint Java (sfj) are supported for use with WebSphere. Is that lack of support a problem? Would you be looking to put the images in to production?

**Comment by cniweb** [comment]
Hello David,

Yes that has been my thought to reduce the image size.
Because of the second question, yes we would like to use the image in production.

Thanks,
Chris

**Comment by davidcurrie** [comment]
Thanks Chris. Whilst the creation of such an image is entirely within the scope an issue on this repo, having it supported is a wider concern. Could I get you to create a [Request for Enhancement](https://www.ibm.com/developerworks/rfe/)?

**Comment by cniweb** [comment]
Hi Dave,

OK, I submit a RFE:
http://www.ibm.com/developerworks/rfe/execute?use_case=viewRfe&CR_ID=101062

Thanks,
Chris

**Comment by davidcurrie** [comment]
Thanks again - I'll leave this issue open as there's the possibility that we might still create the image even if we are unable to declare support for it (e.g. due to constraints on testing resource).

**Comment by cniweb** [comment]
Hi David,

you can use this:
https://github.com/ibmruntimes/ci.docker/tree/master/ibmjava

Thanks,
Chris

**Comment by davidcurrie** [comment]
Thanks Chris - those are the Dockerfiles for the images that I mentioned in my first response. Creating the image really isn't the hard part here. Unfortunately, even though the IBM Java team has made those images available, Alpine is not a supported platform for them.

**Comment by cniweb** [comment]
Hi David,

I see the `ibmjava:8-sfj-alpine` docker image, can we use it with liberty or websphere-traditional?

Thanks,
Chris

**Comment by davidcurrie** [comment]
Hi Chris - you could, but as per my earlier comment, you wouldn't be supported.

**Comment by cniweb** [comment]
Hi David,

why is it not supported? It does not work?

Thanks,
Chris

**Comment by davidcurrie** [comment]
Because it is untested and adding any new platform to our Java and WebSphere test coverage has an implied cost. There is a clause that allows use of OS that are 'similar' those that we support with a requirement that you may be required to recreate any issues on a supported OS. That might cover, say, CentOS vs RHEL, but I'm not sure it would stretch to Alpine.

**Comment by cniweb** [comment]
RHEL is for us a good option!

**Comment by arthurdm** [comment]
Closing this one as we have a [CentOS Dockerfile](https://github.com/WASdev/ci.docker/blob/master/ga/developer/centos/Dockerfile) for WebSphere Liberty and  [Alpine images](https://hub.docker.com/r/library/open-liberty/) for Open Liberty (OSS)
