### ISSUE TITLE
Add Docker Certified Images

### ISSUE THREAD

**Issue by cniweb** [WASdev/ci.docker#116]
Publish Images as Docker Certified Images!

See:
https://success.docker.com/Store#Docker_Certified_Publisher_FAQ

Thanks,
Chris

**Comment by davidcurrie** [comment]
Thanks Chris. Our current images aren't certified as they are produced by Docker themselves (and therefore implicitly certified). We are, however, investigating certified images so I'll keep this issue open.

**Comment by arthurdm** [comment]
@Tom-Banks  / @davidcurrie - any objections to closing this one, as we now have https://store.docker.com/images/ibm-websphere-liberty?

**Comment by davidcurrie** [comment]
The images aren't yet certified though.

**Comment by arthurdm** [comment]
We are now certified: https://store.docker.com/images/websphere-liberty  =)
