### ISSUE TITLE
Dockerfile for webProfile7 and javaee7 missing ampersands

### ISSUE THREAD

**Issue by davidcurrie** [WASdev/ci.docker#121]
webProfile and javaee7 are missing && preceding the echo command
This results in the repositories.properties not being written correctly

https://github.com/WASdev/ci.docker/blob/master/ga/developer/webProfile7/Dockerfile

microProfile and webProfile6 are ok

https://github.com/WASdev/ci.docker/blob/master/ga/developer/microProfile/Dockerfile

**Comment by jamiecoleman92** [comment]
I have now merged in the fix. Please test!

**Comment by jamiecoleman92** [comment]
Confirmed as working. Closing this issue!
