### ISSUE TITLE
Tags for liberty versions

### ISSUE THREAD

**Issue by gcrova** [WASdev/ci.docker#134]
Hello,

Do you have an option to select Liberty version when pulling Docker image? If no, could it be possible to have more tags depending on Liberty version ? 

We are currently relying on webProfile7 but we don't have any option to select the liberty version.

Thanks
Regards
Gael

**Comment by jamiecoleman92** [comment]
Hi Gael

We have the option to select profiles such as webProfile7 or Kernel but we do not have the option to get older versions of our images unless you are looking for 8.5.5.9 and below. You could create your own image from this repository and simply change line 24 in the following file to the version you require: https://github.com/WASdev/ci.docker/blob/master/ga/developer/kernel/Dockerfile

We do not currently have any plans to host images for every version of Liberty

Kind regards

Jamie L Coleman

**Comment by arthurdm** [comment]
Closing this issue with "working as designed".
