### ISSUE TITLE
Dockerfile should make use of entrypoint over cmd

### ISSUE THREAD

**Issue by NottyCode** [WASdev/ci.docker#136]
When putting the open-liberty official image up it was pointed out that we should use an entry point script and a default cmd, which would allow someone to do docker run websphere-liberty <command> rather than have it start the server. 

See https://github.com/OpenLiberty/ci.docker/blob/master/release/kernel/java8/ibmjava/Dockerfile for a good example.

**Comment by arthurdm** [comment]
+1 @NottyCode 

I will look into this

**Comment by arthurdm** [comment]
Fixed via merge #139
