### ISSUE TITLE
Building the kernel docker image failed with wget not found

### ISSUE THREAD

**Issue by chandrams** [WASdev/ci.docker#171]
Building the kernel docker image (ga/developer/kernel/dockerfile) failed with wget not found 

/bin/sh: 1: wget: not found

**Comment by arthurdm** [comment]
hey @chandrams - I tried it right now and it worked for me.

Are you sure you don't have an older IBM JRE image or Ubuntu image cached in your docker registry?

You can run `docker images` to see which images you have cached, then do `docker rmi -f <image_name>`  to remove it.

**Comment by chandrams** [comment]
Sorry I missed a step here, I had replaced 
FROM ibmjava:8-jre with FROM adoptopenjdk/openjdk8-openj9:nightly

and built the docker image, it failed with the above issue. On adding _apt-get install -y --no-install-recommends wget ca-certificates_ it created the docker image

**Comment by arthurdm** [comment]
cool, thanks.  Closing this now.
