### ISSUE TITLE
docker hub websphere-liberty image port forwarding not working

### ISSUE THREAD

**Issue by venkatmarella** [WASdev/ci.docker#175]
Our services are failing with latest docker hub image, old versions working fine.

**Comment by arthurdm** [comment]
Hi @venkatmarella - the `latest` tag is now point to `javaee8`, so if you were relying on `javaee7` you can change your `FROM` statement to `FROM websphere-liberty:javaee7`.

**Comment by arthurdm** [comment]
Hey @venkatmarella - that's strange, as we didn't change anything related to not accepting traffic on a port.  Does your server.xml have `host="*'`? https://github.com/WASdev/ci.docker/blob/master/ga/developer/javaee8/server.xml#L28

**Comment by arthurdm** [comment]
Closing this one.   Please re-open if the problem still persists.
