### ISSUE TITLE
List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)

### ISSUE THREAD

**Issue by shobhit0511** [WASdev/ci.docker#194]
I am getting error like **List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)** when trying to install any OS package in `websphere-liberty:webProfile7` docker image.

My Dockerfile looks like : 

> FROM websphere-liberty:webProfile7
RUN apt-get update
RUN apt-get install -y curl

**Comment by arthurdm** [comment]
hi @shobhit0511 - the image now runs as non-root, so for root-access things you have to switch into root, such as:
```
FROM websphere-liberty:webProfile7
ARG SSL_KEYSTORE_PASSWORD
USER root
RUN apt-get update && 
apt-get install -y 
curl
USER 1001
```

**Comment by shobhit0511** [comment]
@arthurdm Yes it's working,Thanks.

**Comment by arthurdm** [comment]
perfect.  thanks! =)
