### ISSUE TITLE
Docker websphere-liberty:javaee8 continuously transferring data in https

### ISSUE THREAD

**Issue by jmtbusiness** [WASdev/ci.docker#197]
Hello, we use Docker to run a WAS Liberty application.

When starting the javaee8 profile and accessing the https page we get an infinite "Transferring data from localhost", in chrome or firefox there is a small animation left to the url in the browser. However debuging tools at browser level do not show any network activity.

When starting the javaee7 profile and accessing the https page the browser immediately completes the load of the page. 

to reproduce this behaviour: 
docker run -d -p 80:9080 -p 443:9443 websphere-liberty:javaee7
docker run -d -p 81:9080 -p 444:9443 websphere-liberty:javaee8

https://localhost:444 will shows the infinite loop.

**Comment by arthurdm** [comment]
thanks for reporting this @jmtbusiness - I am able to reproduce with your instructions.

@NottyCode - have you seen this before?  I noticed that it happens with the Open Liberty docker image as well, but doesn't happen with standalone (non-docker) binaries.

**Comment by jmtbusiness** [comment]
Could it be the chmod of the .png files ? I noticed that WAS Liberty by default run as user 1001:1001 in Docker

**Comment by arthurdm** [comment]
I thought about that, but the same thing happens if you run `docker run -d -p 81:9080 -p 444:9443 open-liberty:javaee8`, which is still running as root, so probably something else.  Interesting behaviour.  I didn't see this happening on Safari - as you said, only in Firefox and Chrome.

**Comment by covener** [comment]
I can't get this symptom with a variety of clients and docker hosts, does it still occur?  Is there a public or 9.x endpoint I can try a browser against?

**Comment by jmtbusiness** [comment]
Hello, I just downloaded the latest websphere-liberty:javaee8 image which was updated 9 days ago and I can not reproduce the problem with this latest image. The https page loads normally.
Not sure what solved the problem but it's not there any more.
