### ISSUE TITLE
Cannot disable welcome page

### ISSUE THREAD

**Issue by riendeau** [WASdev/ci.docker#237]
The [Liberty documentation](https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.liberty.autogen.base.doc/ae/rwlp_config_httpDispatcher.html) (and [other resources](https://www.ibm.com/developerworks/community/blogs/be0e558a-25e4-48db-91b3-812f6eaa8d3b/entry/How_to_disable_welcome_page_and_server_information_for_WebSphere_Liberty_Profile?lang=en)) suggest that I should be able to disable the Liberty welcome page by adding a line like
```xml
<httpDispatcher enableWelcomePage="false" />
```
...to my server.xml. However, if I build and run a Docker container from a Dockerfile like
```dockerfile
FROM websphere-liberty:19.0.0.2-webProfile8
RUN sed -i 's,</server>,    <httpDispatcher enableWelcomePage="false" />\n</server>,' /config/server.xml
```

...then go to localhost:9080, I still see the Liberty welcome page.

**Comment by arthurdm** [comment]
Thanks for reporting this @riendeau 

I just tried it and I get:

```
Not Found
The application or context root for this request has not been found: /
```

Are you sure you don't have another Liberty container running on 9080?    You could remove all local containers by doing `docker rm -f $(docker ps -aq)`

**Comment by riendeau** [comment]
I did not have another container running on 9080, but this _was_ an oversight on my part. My browser must have had the welcome page in its cache from before I added the `httpDispatcher` line. When I discarded the cache and reloaded, I, too, got the expected `Not Found` error.

Thanks for the sanity check, and apologies for the false alarm.

**Comment by arthurdm** [comment]
awesome.  thanks @riendeau!
