### ISSUE TITLE
Liberty server is not running in non-root user

### ISSUE THREAD

**Issue by prakaashkpk** [WASdev/ci.docker#241]
Liberty server is not running in non-root user

```
>  kubectl exec -it apisvrdeploy-db44cf9bb-s2kzs -n=dev-pro -- /bin/bash
Defaulting container name to apiserver.
Use 'kubectl describe pod/apisvrdeploy-db44cf9bb-s2kzs -n dev-pro' to see all of the containers in this pod.

root@apisvrdeploy-db44cf9bb-s2kzs:/# whoami
root
```

Also may of the files are still owned by root user. for example, 

```
root@apisvrdeploy-db44cf9bb-s2kzs:/opt/ibm/wlp/usr/servers/defaultServer# ls -ltr
total 12
drwxrwx--- 1 default root    6 Mar 12 02:05 apps
-rw-rw---- 1 default root   67 Mar 12 02:05 server.env
drwxrwxr-x 1 default root   22 Mar 12 02:05 configDropins
-rw-rw-r-- 1 root    root 1034 Mar 26 13:27 server.xml
-rw-rw-r-- 1 root    root   94 Mar 26 13:27 jvm.options
lrwxrwxrwx 1 root    root   38 Mar 26 13:33 defaultServer -> /opt/ibm/wlp/usr/servers/defaultServer
drwxrwx--- 1 default root   26 Mar 26 13:33 dropins
```

**Comment by arthurdm** [comment]
hi @prakaashkpk - are you sure you have a recent docker image?      If you look at the logs (`docker logs <container` or `kubectl logs <pod`) it should say at the top which version of WebSphere Liberty it is running.

**Comment by prakaashkpk** [comment]
We are using `websphere-liberty:19.0.0.2-webProfile7`

**Comment by arthurdm** [comment]
When I do `docker run websphere-liberty:19.0.0.2-webProfile7 id` I get `uid=1001(default) gid=0(root) groups=0(root)`, so it seem like it's correct.  

We changed the permissions that were needed, avoiding the ones we didn't need to change to reduce the size of the final image.  Doing `chown` increases the size.

**Comment by arthurdm** [comment]
Closing this one.  If you still see the issue please feel free to repon.

**Comment by prakaashkpk** [comment]
Thanks @arthurdm for the help.
