### ISSUE TITLE
Uninstall packages that are not needed

### ISSUE THREAD

**Issue by arthurdm** [WASdev/ci.docker#247]
The Java layer we depend on currently installs `wget` and Liberty installs `unzip`.  Both of these packages can / should be removed after they are used.

**Comment by sotoiwa** [comment]
@arthurdm Uninstalling wget does not reduce the image size, so I don't think there is much benefit. Is it better not to delete it?

**Comment by arthurdm** [comment]
Hi @sotoiwa - you're correct that it doesn't help the image size since it's being installed in the IBM Java layer.  However, there are 2 reasons for it:
* security concern:  some customers have expressed concern that `wget` was still installed in our images
* future size reduction:  if we can do a similar approach of `install + use + uninstall` in the base IBM Java layer, then Liberty automatically will get a size reduction.

**Comment by sotoiwa** [comment]
@arthurdm Understood the reasons. I think we had better to write `apt-get install wget` in Liberty's Dockerfile.

**Comment by arthurdm** [comment]
Closed as completed.  Thanks @sotoiwa and @Rachelwrq
