### ISSUE TITLE
move to ubuntu 18.0.4.2

### ISSUE THREAD

**Issue by strouja** [WASdev/ci.docker#278]
Hi, I was going to ask for an alpine OS image of liberty docker image and then read this https://github.com/WASdev/ci.docker/issues/107   I think you should move to at least Ubuntu 18.04.2 and possibly use the minimal version of it.   Just to help we have been running Liberty for 2 years in our docker images (that we created)  and moved to Ubuntu 18.0.4.2 a while ago (I think over a year or so).   We are not running the minimal version of the OS which I want us to move to.

My impetus for this are two fold
1) See if we can reduce the docker image footprint of liberty (I read issue 107 and understand the constraints)
2)  Move to a more recent OS (18.0.4.2 vs. 16.04.6). to get the benefits of the new OS improvements.

Also if this issue is redundant we can archive it or something.

Thanks for your work,  James Stroud (PS I am an IBMer)

**Comment by arthurdm** [comment]
Thanks for you feedback @strouja 

We depend on the IBM Java image, so we are waiting for this [PR](https://github.com/ibmruntimes/ci.docker/pull/56) to be merged before we can pick it up.

**Comment by hsaunders0788** [comment]
@arthurdm what's the status on that PR? Is this still blocked or can we move forward with this?

**Comment by arthurdm** [comment]
Still blocked.  I added another comment to the PR we're waiting for.

**Comment by arthurdm** [comment]
Closing this as completed.
