### ISSUE TITLE
Log4j not printing logs to console on liberty Container

### ISSUE THREAD

**Issue by abhiraj-mehrotra** [WASdev/ci.docker#284]
I am using log4j in web project war to print logs to file as well as console. 

When in am running that war on my local liberty, it is working as expected. 
When i am running that in liberty container, logs are going to file and not on console.
Attaching log4j and server.xml in zip.

Liberty version on local:
WebSphere Application Server Version 19.0.0.7 Liberty - (19.0.0.7-cl190720190711-1115)
OS: Windows
Java: IBM JDK 8

Liberty on container:
WebSphere Application Server 19.0.0.7/wlp-1.0.30.cl190720190711-1115
Image:  registry.bluemix.net/ibm/liberty:webProfile8

[log4jand server.zip](https://github.com/WASdev/ci.docker/files/3439262/log4jand.server.zip)

**Comment by donbourne** [comment]
We've opened https://github.ibm.com/was-liberty/WS-CD-Open/issues/17920 to investigate.

**Comment by donbourne** [comment]
@abhiraj-mehrotra , I think you decided this was working as expected... can you please close this one?
