### ISSUE TITLE
no 19.0.0.7 image

### ISSUE THREAD

**Issue by davidkarlsen** [WASdev/ci.docker#285]
I can't find any 19.0.0.7 image available?

**Comment by arthurdm** [comment]
hi @davidkarlsen - we keep the current fixpack under the "version-less" tags (e.g. `websphere-liberty:javaee8`), and the last 2 quarterly fixpacks.  So right now the version-less tags point to `19.0.0.7` and we also have `19.0.0.6` and `19.0.0.3` (last 2 quarterly fixpacks) available.

Very soon we will switch the version-less tag to point to `19.0.0.8`.

**Comment by davidkarlsen** [comment]
I was aware that the version-less were the latest - but in addition there should be the version specific ones to make it predictable what is offered/use a hard version - this has been practice until now - and also seen generally as a best practice. Could you consider doing that?

**Comment by arthurdm** [comment]
that's a valid request @davidkarlsen - the reason we stopped versioning the "in-between-quarter" releases (such as 19.0.0.7 and 19.0.0.8) was that they are only updated for the 4 weeks until the next version, which many customers did not know.   So you could be pointing to a 19.0.0.7 versioned tag and not remember that in 4 weeks that image will stop receiving updates.

**Comment by davidkarlsen** [comment]
They need to do some action to get the update anyway (pull image, rebuild) -  having the version it actually is (in addition to the version-less) just makes it a lot more visible, predictable and transparent - you now need to do some detective work to figure out what the underlying version is. It is also some friction towards re-buildability - say you provide some internal version with additions/common configuration - then that's a moving target without any control.

**Comment by davidkarlsen** [comment]
I like this scheme: https://hub.docker.com/_/ubuntu/

**Comment by davidkarlsen** [comment]
@arthurdm Did you give this any consideration?

**Comment by arthurdm** [comment]
hey @davidkarlsen - yes, we have considered the pros and cons, and at this time we will keep the versioning as-is.    Given how fast these versions move (every 4 weeks), the guidance is that if you need to build internal images based on a particular Liberty version you just pick the last versioned base image - which will never be older than 3 months.   

That will ensure you are building on something that will continue to receive security updates, etc.  For example right now the 19.0.0.7 version (if we had one) wouldn't be receiving security updates, and most customers wouldn't know that.
