### ISSUE TITLE
Liberty Tools broken by the latest websphere-liberty docker image

### ISSUE THREAD

**Issue by eharris369** [WASdev/ci.docker#287]
The keystore.xml file has been removed from the latest websphere-liberty docker image which is causing problems for the tools.  The tools present an error dialog to the user if ssl or transportSecurity is enabled but there is no keyStore element.  The default docker image that is created has the javaee-8.0 feature enabled but now that the keystore.xml is removed there is no keyStore element causing the tools to show the dialog.  In the next release of the tools we could work around this but older versions of the tools will be broken.

**Comment by arthurdm** [comment]
thanks @eharris369 - we will investigate if we can keep the same behaviour.

**Comment by arthurdm** [comment]
@arturdzm - perhaps in we can:
- add `KEYSTORE_REQUIRED=true` back into `kernel`
- add an `else if KEYSTORE_REQUIRED=true` statement [here](https://github.com/WASdev/ci.docker/blob/master/ga/latest/kernel/helpers/runtime/docker-server.sh#L36) which then changes `keystorePath` to be `/config/configDropins/defaults/keystore.xml` and does [this](https://github.com/WASdev/ci.docker/blob/master/ga/latest/kernel/helpers/runtime/docker-server.sh#L36)?

**Comment by arthurdm** [comment]
or we could simply add `TLS=true` in the `kernel`, but change its target location to be the `defaults` folder instead of the `overrides` folder.

**Comment by arthurdm** [comment]
The fix has been delivered and confirmed.
