### ISSUE TITLE
LIBERTY_URL is set to null when LIBERTY_VERSION is 19.0.0_08

### ISSUE THREAD

**Issue by nidhi1605** [WASdev/ci.docker#290]
In https://github.com/WASdev/ci.docker/blob/master/ga/latest/kernel/Dockerfile, ```wget -q -O - https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/index.yml | grep $LIBERTY_VERSION -A 6 ``` returns null as there is no 19.0.0_08 Liberty version present at https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/index.yml. Because of this the docker build of the image fails.

**Comment by arthurdm** [comment]
Thanks @nidhi1605 - we're looking to update this soon.

**Comment by nidhi1605** [comment]
Fixed in #291
