### ISSUE TITLE
Wrong java version embedded in docker image of Websphere Liberty 19.0.0.9

### ISSUE THREAD

**Issue by StephaneVINCENT-IBM** [WASdev/ci.docker#293]
Websphere Liberty **19.0.0.9** is supposed to embed the IBM JRE **8 SR5 FP40**.
Source: https://cloud.ibm.com/docs/runtimes/liberty?topic=liberty-latest_updates#latest_updates

After using the following commands:
```
docker pull ibmcom/websphere-liberty:microProfile1-ubi-min
docker run -ti --rm=true ibmcom/websphere-liberty:microProfile1-ubi-min
```

The IBM JRE version is the previous one (8.0.5.37) and not the expected one (8.0.5.40):
```
Launching defaultServer (WebSphere Application Server 19.0.0.9/wlp-1.0.32.cl190920190905-0148) on IBM J9 VM, version 8.0.5.37 - pxa6480sr5fp37-20190618_01(SR5 FP37) Small Footprint (en_US)
```
Please fix this issue and keep me informed
Thank you

**Comment by arthurdm** [comment]
@StephaneVINCENT-IBM - the link you provided is for the Cloud Foundry buildpack, which is different than our Docker images.  

We always build our Docker images using the latest available IBM Java images, we don't specify particular versions.

**Comment by StephaneVINCENT-IBM** [comment]
Sorry but the latest available IBM Java Image is IBM JRE **8.0.5.40** (not 8.0.5.37).

For futher information:
https://github.com/ibmruntimes/ci.docker/blob/master/ibmjava/8/jre/ubi-min/Dockerfile

So please reopen this ticket and fix this issue.

**Comment by arthurdm** [comment]
interesting - something wasn't synchronized properly.   we'll get it updated.

**Comment by arthurdm** [comment]
this has been fixed.
