### ISSUE TITLE
When will 19.0.0.10 and 19.0.0.11 be available for the community images?

### ISSUE THREAD

**Issue by sturcol** [WASdev/ci.docker#299]
Our team has many different requirements to move up to 19.0.0.10 (or later). What is the release schedule for the community images?

**Comment by arthurdm** [comment]
Hi @sturcol - we have updated the UBI page (https://hub.docker.com/r/ibmcom/websphere-liberty) to list the new tags that we have.  The version-less tags are currently supporting 19.0.0.11

**Comment by sturcol** [comment]
Thanks for the info. Do you not add the version tag for the latest? IE, should I not expect to see 19.0.0.11-kernel-ubi-min until that is the n-1 version

**Comment by sturcol** [comment]
Thanks for the info @arthurdm . Do you not add the version tag for the latest? IE, should I not expect to see 19.0.0.11-kernel-ubi-min until that is the n-1 version

**Comment by arthurdm** [comment]
we only add version for the "quarterly boundary" images, such as 19.0.0.6, 19.0.0.9 and the upcoming 19.0.0.12, as those receive security updates.  The versions in-between (such as 19.0.0.10 and 19.0.0.11) stop receiving security updates as soon as the next fixpack is available, so those just roll over under the latest tags.

**Comment by arthurdm** [comment]
Closing this one.  Please re-open if still not clear.
