### ISSUE TITLE
Licensing in Websphere Liberty docker image

### ISSUE THREAD

**Issue by kvenkatramreddy** [WASdev/ci.docker#319]
Hi Team,

How licensing works with Websphere Liberty with docker images.

As per my knowledge, there are 3 licensing models in Websphere Liberty

1) Core
2) Base
3) ND

Please let me know how can I get a docker image for only core edition?

Thanks & Regards,
Venkat

**Comment by arthurdm** [comment]
Hi @kvenkatramreddy - the best way to do that is to start with the WebSphere Liberty kernel tag, then add the core license (info in [here](https://github.com/WASdev/ci.docker/tree/master/ga/production-upgrade#using-websphere-liberty-docker-in-production)), and then run `configure.sh` at the end of your Dockerfile to install the features you need (the core license jar will ensure you only get core features).

**Comment by arthurdm** [comment]
Closing this one. Please let us know if you have any more questions.
