### ISSUE TITLE
configure.sh fails in image 19.0.0.9-javaee7-ubi-min with xargs: command not found

### ISSUE THREAD

**Issue by alexwoodgate** [WASdev/ci.docker#320]
I've tried to use the latest built image 19.0.0.9-javaee7-ubi-min and configure.sh fails to find the xargs and find commands. This did work a few weeks ago (I think an older image built on 2019-12-18 which we had pulled worked), and no obvious changes in the area in this repo, so I assume it's a change one of the parent images that configure.sh doesn't work with.

Recreate steps:
1. Get the latest image:
docker pull ibmcom/websphere-liberty:19.0.0.9-javaee7-ubi-min
2. Build with Dockerfile (a simplified version of the readme example):
```
FROM ibmcom/websphere-liberty:19.0.0.9-javaee7-ubi-min
# Optional functionality
ARG SSL=true
ARG MP_MONITORING=true
# Default setting for the verbose option
ARG VERBOSE=true
# This script will add the requested XML snippets, grow image to be fit-for-purpose and apply interim fixes
RUN configure.sh
```

Using VERBOSE=true the last bit of output shows:
[docker.log](https://github.com/WASdev/ci.docker/files/4298662/docker.log)
```
Product validation completed successfully.
+ find /opt/ibm/fixes -type f -name '*.jar' -print0
+ sort -z
/opt/ibm/helpers/build/configure.sh: line 106: find: command not found
+ xargs -0 -n 1 -r -I '{}' java -jar '{}' --installLocation /opt/ibm/wlp
/opt/ibm/helpers/build/configure.sh: line 106: xargs: command not found
The command '/bin/sh -c configure.sh' returned a non-zero code: 127
```

**Comment by edavidj** [comment]
Thanks for opening this @alexwoodgate, I was also able to reproduce locally. I think this is related to changes to our build scripts a few weeks back, I'll investigate.

**Comment by edavidj** [comment]
@alexwoodgate I believe the issue should be resolved now. Can you confirm?

**Comment by alexwoodgate** [comment]
I pulled the latest image and configure.sh works again for me now. Thanks!
