### ISSUE TITLE
set REPOSIROTIES_PROPERTIES build-arg

### ISSUE THREAD

**Issue by zhanglm2004** [WASdev/ci.docker#329]
repositories.property usually contains multiple lines, for example the proxy settings; how do we  set build-arg REPOSITORIES_PROPERTIES when  multi-lines needed?  could anyone give an example ?  Thanks

**Comment by arthurdm** [comment]
hi @zhanglm2004 - you could use the `\n` delimiter, like this example:

```
ARG REPOSITORIES_PROPERTIES="useDefaultRepository=false\nlocal-rep.url=/tmp/repo.zip"
 ```

**Comment by zhanglm2004** [comment]
Thanks a lot!   It looks like it would work if I put double quote around, like  "$REPOSITORIES_PROPERTIES"
