### ISSUE TITLE
Prevent duplication of directory tree at /opt/ibm/wlp in application docker images

### ISSUE THREAD

**Issue by ashu-mehra** [WASdev/ci.docker#334]
I am trying to port the fix https://github.com/OpenLiberty/ci.docker/pull/166 to webshpere-liberty docker images. But it looks like this fix alone is not sufficient to make the common SCC layer shareable.
This is because the `configure.sh` script is also changing the permission of parent directory using following commands:
https://github.com/WASdev/ci.docker/blob/8571f13a63cd0767e2ba6af3fcd0001c0e636e59/ga/latest/kernel/helpers/build/configure.sh#L108
https://github.com/WASdev/ci.docker/blob/8571f13a63cd0767e2ba6af3fcd0001c0e636e59/ga/latest/kernel/helpers/build/configure.sh#L115

Note that these commands will cause duplication of whole directory tree rooted at `/opt/ibm/wlp/` in the application specific docker image if the dockerfile happens to call `configure.sh`.

I think these commands should instead grant group write permissions only to folder which get affected by installing new features. But I am not sure which folders would they be.
Again, I am not sure I understand the need to make `/opt/ibm/wlp` executable for the group but I am wondering if we can limit it to just `/opt/ibm/wlp/bin` directory and move the command to the base Dockerfile so that application docker images won't be affected.

Another issue is the command to install interim fixes:
https://github.com/WASdev/ci.docker/blob/8571f13a63cd0767e2ba6af3fcd0001c0e636e59/ga/latest/kernel/helpers/build/configure.sh#L106

It invokes JVM which by default would try to use common layer of shared class cache causing it to be duplicated when building app docker image. 

If we want to execute the above command to install fixes during application docker image build process, then I think we should ensure the JVM runs without using SCC by appending `-Xshareclasses:none` to env variables, the way it is done in `installUtility` script:

```
# Do not create a SCC
if [ -n "${IBM_JAVA_OPTIONS}" ]; then
  IBM_JAVA_OPTIONS="${IBM_JAVA_OPTIONS} -Xshareclasses:none"
fi

if [ -n "${OPENJ9_JAVA_OPTIONS}" ]; then
  OPENJ9_JAVA_OPTIONS="${OPENJ9_JAVA_OPTIONS} -Xshareclasses:none"
fi
```

**Comment by arthurdm** [comment]
@arturdzm - can you please check out the suggestions by @ashu-mehra?

**Comment by ashu-mehra** [comment]
Another alternative for granting group access is to set the `umask` (to 002 I think). That way we wouldn't have to worry about doing `chmod` on every new directory that gets created.

**Comment by leochr** [comment]
I believe https://github.com/WASdev/ci.docker/pull/395 resolves this. @ashu-mehra / @jdmcclur please close if you agree.
