### ISSUE TITLE
Update mountPath in Infinispan secret sample yaml

### ISSUE THREAD

**Issue by alexsm82** [WASdev/ci.docker#339]
The Infinispan generated secret must be mounted at `/platform/bindings/secret/` but in the sample yaml the mountPath listed is `/config/liberty-infinispan-secret`. The mount path should be updated to `/platform/bindings/secret/`.

**Comment by arthurdm** [comment]
thanks @alexsm82 - yes, we need to fix the doc.

The service binding spec is being updated to have the service id in the path, so we should change the default (in the upcoming `latest` stream) to  `/platform/bindings/infinispan/secret`.

**Comment by arthurdm** [comment]
Also applies to Open Liberty.

**Comment by edavidj** [comment]
Updated in Open Liberty and WASdev 👍
