### ISSUE TITLE
Is there any plan to support UBI 7?

### ISSUE THREAD

**Issue by Daiki-Kawanuma** [WASdev/ci.docker#341]
I know there are only Liberty Image based on UBI 8.

According to Red Hat support policy, UBI and host OS RHEL(and CoreOS?) version should be same. But now, OpenShift 4 request RHEL 7 so that Liberty image based on UBI 8 is not guaranteed to run on OpenShift 4.
https://access.redhat.com/support/policy/rhel-container-compatibility

I would like to request UBI 7 support. Is there any plan to support UBI 7?

**Comment by arthurdm** [comment]
hi @Daiki-Kawanuma - I think there may be some confusion, because OCP 4 definitely supports RHEL 8 / UBI 8.

**Comment by Daiki-Kawanuma** [comment]
Hi @arthurdm 
Could you please confirm Red Hat Official Document which says that we can use only RHEL 7.6 as compute machine?
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.4/html/installing_on_vsphere/installing-on-vsphere#installation-requirements-user-infra_installing-vsphere
<img width="680" alt="image" src="https://user-images.githubusercontent.com/15085341/83090181-28b95680-a0d3-11ea-9b9f-054f775ce74e.png">

As you say, UBI 8 and RHCOS(based on RHEL 8) is supported but in some case, we have to use RHEL instead of RHCOS, so that I want to get WAS image based on UBI 7.

**Comment by arthurdm** [comment]
I see.  Unfortunately we don't have any plans to produce older UBI  7 images any more.  We are now at UBI 8.2 with our UBI-based images.

**Comment by arthurdm** [comment]
You can still use UBI 8 on RHEL 7 hosts, it's just not the recommended path.  But it's still supported according to the first doc.

**Comment by arthurdm** [comment]
Closing this one, as our strategic version for UBI is 8.
