### ISSUE TITLE
Push latest images also with version tag

### ISSUE THREAD

**Issue by Manu206** [WASdev/ci.docker#352]
It would be really great if you could also push the latest images that are tagged like e.g. `kernel-java8-ibmjava-ubi` in addition with the corresponding version. Usually we try whenever possible to specify a fixed version instead of a changing tag as this will reduce possible failures in case an automated rebuild happens.

Currently there is a tag `20.0.0.6-kernel-java8-ibmjava-ubi` however the tag `20.0.0.7-kernel-java8-ibmjava-ubi` is missing. The `20.0.0.7-kernel-java8-ibmjava-ubi` is available as `kernel-java8-ibmjava-ubi`. Basically all I'm asking is to also push the tag `20.0.0.7-kernel-java8-ibmjava-ubi` (would be good if this could be the default approach and future releases will also have a version in the tag).

**Comment by arthurdm** [comment]
@edavidj - I thought we were already publishing the non-quarterly UBI images with their version in the tag as well.     is there something in the build that's preventing it for going through?

**Comment by edavidj** [comment]
@arthurdm Yes this should be what happens, I seem to have forgotten to update that. I think some confusion gets introduced when the previous latest was a quarterly release like 20.0.0.6 as it would have been pushing one less version effectively. I'll add a PR template with a checklist to future proof against that issue.

I'll update the tags now, should be pushed to Docker Hub by late afternoon👍

**Comment by arthurdm** [comment]
cool, thanks @edavidj!

**Comment by Manu206** [comment]
Thank you
