### ISSUE TITLE
ARM64 Support 

### ISSUE THREAD

**Issue by odidev** [WASdev/ci.docker#379]
Hi Team,

I am trying to use the **websphere-liberty** image on the arm64 platform but it seems it is not available for arm64.

It looks there are multiple dockerfiles present and also the base image being used in the dockerfiles is not available for arm64.

Do you have any plans on releasing arm64 images?

It will be very helpful if the image is released with ARM64 support. If required, I am happy to contribute.

**Comment by tanjunchen** [comment]
@odidev  do you have build websphere-liberty  arm64 images?

**Comment by leochr** [comment]
arm64 images are now added for Ubuntu images: https://hub.docker.com/_/websphere-liberty/

Note that IBM Java images don't support arm64, hence Liberty images with IBM Java are not available for arm64. Rest of the Liberty images support arm64.

UBI-based images also support arm64. They are available from icr.io and are listed here: https://ibm.biz/wl-images-icr
