### ISSUE TITLE
Update images to have feature.sh like Open. Liberty images

### ISSUE THREAD

**Issue by NottyCode** [WASdev/ci.docker#382]

**Comment by leochr** [comment]
As this would be a breaking change, use a new tag name (i.e. `kernel-slim`). The `kernel` tag would be deprecated.

**Comment by leochr** [comment]
features.sh will be introduced as part of existing `kernel` images. If features.sh hasn't been invoked, then invoke it as part of configure.sh. Document the new process to build application images with features.sh (similar to [Open Liberty](https://github.com/OpenLiberty/ci.docker#building-an-application-image))
