### ISSUE TITLE
Warning message when pulling Liberty Profile image

### ISSUE THREAD

**Issue by arun-gupta** [WASdev/ci.docker#39]
Pulling the latest Websphere Liberty image shows the following warning:

```
Status: Downloaded newer image for websphere-liberty:latest
docker.io/library/websphere-liberty: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.
```

Seems like the image needs to be refreshed with a more recent version.

**Comment by davidcurrie** [comment]
@arun-gupta I would have said this was a Hub issue rather than an image issue but, given that the images were rebuilt last night following the update to our December beta, I may never know! I don't see this error today using a 1.9.1 client. Please re-open if you're still seeing the problem.
