### ISSUE TITLE
Fix image names not done for 21.0.0.6 

### ISSUE THREAD

**Issue by lmgray** [WASdev/ci.docker#401]
It looks like 21.0.0.6 was released yesterday, but name fixup wasn't done:

for example:

> [**ga/latest/kernel/Dockerfile.ubi.ibmjava8:36**](https://github.com/WASdev/ci.docker/blob/8d30234391a62a3a6b2c32b45801cb5e914781fa/ga/latest/kernel/Dockerfile.ubi.ibmjava8#L36)
> 
> ENV LIBERTY\_VERSION 21.0.0\_05

but

there's no 21.0.0\_05 in [https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/index.yml](https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/index.yml)

**Comment by leochr** [comment]
@lmgray We are in the process of producing and pushing the images for 21.0.0.6. Expect them to be available early next week.

**Comment by lmgray** [comment]
thanks for the update...  wonder if, in the future, maybe the name fixup could be more tightly coupled to the release?  we have internal build automation that rebuilds liberty daily to pick up secfixes etc.  We just pull in [https://github.com/WASdev/ci.docker/blob/master/ga/latest/kernel/Dockerfile.ubi.ibmjava8](https://github.com/WASdev/ci.docker/blob/master/ga/latest/kernel/Dockerfile.ubi.ibmjava8) and append local changes...

I see the fixup has now been done so we should be good to go with out builds now -- thanks!

**Comment by leochr** [comment]
The current build infrastructure setup requires the Liberty binaries to be published externally before the images can be built. We'll look at improving that to reduce the time between binary and image release.
