### ISSUE TITLE
docker build broken

### ISSUE THREAD

**Issue by lmgray** [WASdev/ci.docker#434]
Our in-house Liberty build broke yesterday...

It looks like Liberty Dockerfile doesn't agree with downloads -- it looks like Download index got ahead of Dockerfile:

Dockerfile lists:

```
Step 9/25 : ENV LIBERTY_VERSION 22.0.0_01`
```

but index.yml doesn't contain 22.0.0\_01 :

\`\`\`  
\# version: uri  
\---

21.0.0\_09:  
   license: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/21.0.0.9/lafiles/runtime/en.html  
   kernel: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/21.0.0.9/wlp-kernel-21.0.0.9.zip  
   webProfile7: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/21.0.0.9/wlp-webProfile7-21.0.0.9.zip  
   javaee7: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/21.0.0.9/wlp-javaee7-21.0.0.9.zip  
   microProfile1: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/21.0.0.9/wlp-microProfile1-21.0.0.9.zip  
   webProfile8: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/21.0.0.9/wlp-webProfile8-21.0.0.9.zip  
   javaee8: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/21.0.0.9/wlp-javaee8-21.0.0.9.zip

22.0.0\_02:  
   license: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/22.0.0.2/lafiles/runtime/en.html  
   kernel: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/22.0.0.2/wlp-kernel-22.0.0.2.zip  
   webProfile7: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/22.0.0.2/wlp-webProfile7-22.0.0.2.zip  
   javaee7: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/22.0.0.2/wlp-javaee7-22.0.0.2.zip  
   microProfile1: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/22.0.0.2/wlp-microProfile1-22.0.0.2.zip  
   webProfile8: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/22.0.0.2/wlp-webProfile8-22.0.0.2.zip  
   javaee8: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/22.0.0.2/wlp-javaee8-22.0.0.2.zip

21.0.0\_12:  
   license: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/21.0.0.12/lafiles/runtime/en.html  
   kernel: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/21.0.0.12/wlp-kernel-21.0.0.12.zip  
   webProfile7: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/21.0.0.12/wlp-webProfile7-21.0.0.12.zip  
   javaee7: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/21.0.0.12/wlp-javaee7-21.0.0.12.zip  
   microProfile1: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/21.0.0.12/wlp-microProfile1-21.0.0.12.zip  
   webProfile8: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/21.0.0.12/wlp-webProfile8-21.0.0.12.zip  
   javaee8: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/21.0.0.12/wlp-javaee8-21.0.0.12.zip

8.5.5\_09:  
   uri: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/8.5.5.9/wlp-runtime-8.5.5.9.jar  
   license: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/8.5.5.9/lafiles/runtime/en.html  
   extended: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/8.5.5.9/wlp-extended-8.5.5.9.jar  
   kernel: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/8.5.5.9/wlp-kernel-8.5.5.9.zip  
   webProfile7: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/8.5.5.9/wlp-webProfile7-8.5.5.9.zip  
   javaee7: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/8.5.5.9/wlp-javaee7-8.5.5.9.zip

2020.10.0\_0:  
  license: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/beta/lafiles/en.html  
  webProfile7: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/beta/wlp-beta-2020.10.0.0.zip

2020.11.0\_0:  
  license: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/beta/lafiles/en.html  
  webProfile7: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/beta/wlp-beta-2020.11.0.0.zip  
\`\`\`

**Comment by leochr** [comment]
@lmgray Thank you for reaching out. The _index.yml_ is updated when a new monthly release is available. In this case, 22.0.0.2 was released recently, hence 22.0.0.1 is no longer listed. The last 2 quarterly releases (21.0.0.12 and 21.0.0.9) along with the latest monthly release are listed. 

We've updated the Dockerfiles for 22.0.0.2. Please use that (or one of the quarterly releases). Let us know if you have any further questions or require assistance. Thank you.

**Comment by lmgray** [comment]
With the updated Dockerfiles you committed today, our build is working fine again.  This problem has occurred before, but does not happen on every new release.  It seems like sometimes the index.yml is updated separately from the Dockerfiles and other times the updates are better coordinated.  Is there some reason the updates are not always coordinated?  Should we just accept that when new releases come out, we can expect a couple of days of broken builds until the Dockerfiles catch up?  i.e. should we just be more patient or is it helpful to raise an issue like I did here?

**Comment by lmgray** [comment]
duplicates #401

**Comment by leochr** [comment]
There is a delay between the Liberty binary release and the container image update/release. The process relies on the binary as well as its metadata to be available (they are referenced in the Dockerfiles). It's usually a few days but could take up to a week (if some unexpected issues arise).

**Comment by lmgray** [comment]
OK -- I'll try to remember this and be more patient.  Many thanks @leochr !
