### ISSUE TITLE
Provide official arm64 ubuntu based docker images

### ISSUE THREAD

**Issue by semihalf-mazur-hubert** [WASdev/ci.docker#444]
Hi,
Can you provide official docker images for arm64 arch?
The ubuntu based ones support many architectures except arm64. I performed some tests and the arm64 images are built without any issues and works fine. The `kernel` image is based on ibm-semeru-runtimes which already supports arm64. Is there any particular reason, why arm64 is not yet supported?

I'm ready to contribute if needed to add support for arm64.

Thanks!

**Comment by leochr** [comment]
@semihalf-mazur-hubert The container images for arm64 could only be provided once Liberty runtime officially supports it.

**Comment by leochr** [comment]
arm64 images are now added for Ubuntu images: https://hub.docker.com/_/websphere-liberty/

Note that IBM Java images don't support arm64, hence Liberty images with IBM Java are not available for arm64. Rest of the Liberty images support arm64.

UBI-based images also support arm64. They are available from icr.io and are listed here: https://ibm.biz/wl-images-icr

**Comment by leochr** [comment]
Delivered. Closing
