### ISSUE TITLE
Provide an iFix install process same as Open Liberty

### ISSUE THREAD

**Issue by leochr** [WASdev/ci.docker#456]
The iFixes for WL are added to /opt/ibm/fixes while Open Liberty uses /opt/ol/fixe. This means the application Dockerfile would have to be changed when switching between OL and WL. 

Evaluate and implement a way to provide the same iFix install process. One option to consider is keeping the current paths, but adding a symlink. If this works, update the sample Dockerfile in readme.

**Comment by kabicin** [comment]
It seems our base images already provide the functional change that we need.

For example,
https://github.com/WASdev/ci.docker/blob/5d3733f9b0747b972029a1ed0a58063a59711070/ga/latest/kernel/Dockerfile.ubi.openjdk11#L92
and
https://github.com/OpenLiberty/ci.docker/blob/0f35901f491bd0ff04f2b502fc9cad24fc97721a/releases/latest/kernel-slim/Dockerfile.ubi.openjdk11#L65

So it is just a matter of updating our docs in `applying-ifixes/README.md`
`/opt/ibm/fixes` -> `/liberty/fixes/` (WASDev/ci.docker)
`/opt/ol/fixes` -> `/liberty/fixes/` (OpenLiberty/ci.docker)

**Comment by kabicin** [comment]
The `/liberty` symlink issue can be decoupled from the `/fixes` symlink PR and deferred to another date. Let's use #474 to track `/liberty` symlink update for a future date and add to the Epic.
