### ISSUE TITLE
Wrong /liberty symbolic link

### ISSUE THREAD

**Issue by jgawor** [WASdev/ci.docker#474]
The `/liberty` symbolic link appears to be incorrect. It should point to `/opt/ibm/wlp` instead of `/opt/ibm/`. This would make it consistent with the Open Liberty images. See https://github.com/WASdev/ci.docker/blob/main/ga/latest/kernel/Dockerfile.ubi.ibmjava8#L91 vs https://github.com/OpenLiberty/ci.docker/blob/main/releases/latest/kernel-slim/Dockerfile.ubi.ibmjava8#L65.

**Comment by kabicin** [comment]
Thank you for bringing this up, we are aware of this discrepancy between OL and WL images. It is a breaking change for those who currently depend on the symlink to `/opt/ibm` so we may decide to delay this fix until a later date.

**Comment by leochr** [comment]
Resolved in 23.0.0.7 and above
