### ISSUE TITLE
Wrong version name leads to build errors of Dockerfile

### ISSUE THREAD

**Issue by bqcuong** [WASdev/ci.docker#499]
Hi there,

I was not able to build a kernel image ([ga/23.0.0.3/kernel/Dockerfile.ubuntu.openjdk11](https://github.com/WASdev/ci.docker/blob/a1858e2b54987a75536dbb6a984cfe2056240958/ga/23.0.0.3/kernel/Dockerfile.ubuntu.openjdk11)) on this repository.

I think there is a mistake in the `LIBERTY_VERSION` in the Dockerfile.
That is, the line `ENV LIBERTY_VERSION 23.0.0.3` should be changed to `ENV LIBERTY_VERSION 23.0.0_3`

Below is the log with errors when I tried to build the mentioned Dockerfile.
```bash
...
warning [/tmp/wlp.zip]:  14260646 extra bytes at beginning or within zipfile
  (attempting to process anyway)
The command '/bin/sh -c apt-get update     && apt-get install -y --no-install-recommends unzip wget openssl     && rm -rf /var/lib/apt/lists/*     && mkdir -p /licenses/     && useradd -u 1001 -r -g 0 -s /usr/sbin/nologin default     && LIBERTY_URL=${LIBERTY_URL:-$(wget -q -O - https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/index.yml  | grep $LIBERTY_VERSION -A 6 | sed -n 's/\s*kernel:\s//p' | tr -d '\r' )}      && echo "$LIBERTY_URL"     && wget $DOWNLOAD_OPTIONS $LIBERTY_URL -U UA-IBM-WebSphere-Liberty-Docker -O /tmp/wlp.zip     && unzip -q /tmp/wlp.zip -d /opt/ibm' returned a non-zero code: 1
```

Thanks!

**Comment by Mitchell-Mulder** [comment]
I am also hitting the same issue trying to build [Dockerfile.ubi.ibmjava8](https://github.com/WASdev/ci.docker/blob/main/ga/latest/kernel/Dockerfile.ubi.ibmjava8)

**Comment by leochr** [comment]
Thanks for reporting the issue. Fixed via https://github.com/WASdev/ci.docker/pull/500
