### ISSUE TITLE
Passing custom server.env

### ISSUE THREAD

**Issue by tur-ing** [WASdev/ci.docker#53]
How can I pass a custom server.env to the Container?

**Comment by davidcurrie** [comment]
Hi - you have two options:

You can build it in to an image, for example with a Dockerfile along the lines of:

```
FROM websphere-liberty
COPY server.env /config/server.env
```

or you could mount it in from the file system at runtime e.g.

```
docker run -d -v /tmp/server.env:/config/server.env websphere-liberty
```

**Comment by tur-ing** [comment]
Thanks David!
