### ISSUE TITLE
keystore password regenerated on container restart

### ISSUE THREAD

**Issue by davidcurrie** [WASdev/ci.docker#68]
The new logic for generating a keystore stanza get driven every time a container starts and will therefore generate a new password when a container is restarted. This needs fixing (and we should add at least one test that restarts a container along the way).

**Comment by liamawhite** [comment]
@davidcurrie Just did a fix for this, check my PR.

**Comment by davidcurrie** [comment]
Resolved by https://github.com/WASdev/ci.docker/issues/71
